<?php

declare(strict_types=1);

namespace App\Form\Common;

use App\Core\DataType\RoleDataType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RolesChoiceType extends AbstractType
{
    public function getParent(): string
    {
        return ChoiceType::class; // TODO: Change the autogenerated stub
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'choices' => [
                'Role Admin for Page' => RoleDataType::ROLE_ADMIN_PAGE,
                'Role Admin for Post' => RoleDataType::ROLE_ADMIN_POST,
                'Role Admin' => RoleDataType::ROLE_ADMIN,
                'Role Admin for setting' => RoleDataType::ROLE_ADMIN_SETTING,
            ],
            'attr' => [
                'data-controller' => 'select2',
                'data-select2-placeholder-value' => '-- Select option --',
                'data-select2-dropdown-parent-value' => '#app-modal',
                'class' => 'form-select form-select-sm'
            ],
            'placeholder' => '-- Select option --',
            'multiple' => true,
        ]);

//        $resolver->setDefined(['data-select2-dropdown-parent-value']);
//        $resolver->setDefined(['data-select2-hidden-search-value']);
//
//        $resolver->setNormalizer('attr', function (Options $options, $value) {
//            if (isset($options['data-select2-dropdown-parent-value'])) {
//                $value['data-select2-dropdown-parent-value'] = $options['data-select2-dropdown-parent-value'];
//            }
//            if (isset($options['data-select2-hidden-search-value'])) {
//                $value['data-select2-hidden-search-value'] = $options['data-select2-hidden-search-value'];
//            }
//            return $value;
//        });
    }
}
