parameters:
  blocks_type:
    single_banner_block:
      name: 'Single Banner block'
      backend:
        view: 'Admin/views/blockPreview/single_banner.html.twig'
        controller: 'App\Controller\Admin\Block\BlockCommon::edit'
      frontend:
        view: '%themes%block/single_banner.html.twig'
        controller: ''

    contact_form_block:
      name: 'Contact Form Block'
      backend:
        view: 'Admin/views/blockPreview/contact_form.html.twig'
        controller: 'App\Controller\Admin\Block\BlockCommon::edit'
      frontend:
        view: '%themes%block/contact_form.html.twig'
        controller: ''

    listing_news_article_block:
      name: 'Listing News Article Block'
      backend:
        view: 'Admin/views/blockPreview/listing_news_article.html.twig'
        controller: 'App\Controller\Admin\Block\BlockCommon::edit'
      frontend:
        view: '%themes%block/listing_news_article.html.twig'
        controller: ''

    qas_block:
      name: 'Qas block'
      backend:
        view: 'Admin/views/blockPreview/qas.html.twig'
        controller: 'App\Controller\Admin\Block\BlockCommon::edit'
      frontend:
        view: '%themes%block/qas.html.twig'
        controller: ''

    about_trade_and_food_services_block:
      name: 'About Trade and food services block'
      backend:
        view: 'Admin/views/blockPreview/about_trade_and_food_services.html.twig'
        controller: 'App\Controller\Admin\Block\BlockCommon::edit'
      frontend:
        view: '%themes%block/about_trade_and_food_services.html.twig'
        controller: ''

    listing_prune_trade_and_food_services_block:
      name: 'Listing Prune Trade and food services block'
      backend:
        view: 'Admin/views/blockPreview/listing_prune_trade_and_food_services.html.twig'
        controller: 'App\Controller\Admin\Block\BlockCommon::edit'
      frontend:
        view: '%themes%block/listing_prune_trade_and_food_services.html.twig'
        controller: ''

    manufacturer_block:
      name: 'Manufacturer Block'
      backend:
        view: 'Admin/views/blockPreview/single_banner.html.twig'
        controller: 'App\Controller\Admin\Block\BlockCommon::edit'
      frontend:
        view: '%themes%block/manufacturer.html.twig'
        controller: ''
    growing_harvesting:
      name: 'Growing Harvesting'
      backend:
        view: 'Admin/views/blockPreview/single_banner.html.twig'
        controller: 'App\Controller\Admin\Block\BlockCommon::edit'
      frontend:
        view: '%themes%block/growing_harvesting.html.twig'
        controller: ''
