controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

redirect_to_cms:
    path: /cms
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_admin_page_index
        permanent: true